name: Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run latest-tag
        uses: EndBug/latest-tag@latest

      - run: |
          mv lib/target/libdwarf.jar src
          mv src ghidra2dwarf
          zip ghidra2dwarf.zip ghidra2dwarf/libdwarf.jar ghidra2dwarf/ghidra2dwarf.py ghidra2dwarf/elf.py

      - name: Release file
        uses: djnicholson/release-action@v2.11
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          asset-name: 'ghidra2dwarf.zip'
          file: 'ghidra2dwarf.zip'
          tag-name: 'latest'
          release-name: 'Latest build'
